adding material compliant modals
Chalarangelo/mini.css pull request #118
Opened 2017-11-27 06:37 UTC by spkellydev

2017-11-27 08:55 UTC, Chalarangelo requested changes
These changes should be made to the flavor file and be recompiled into the css and minified css files. If you have the time, please update the flavor file in the /src/flavors/ folder, otherwise I will merge and do this myself sometime later.

2017-11-27 08:56 UTC, Chalarangelo commented
Overall, I am not against the modal in the PWA flavor, I can't even remember why I cut it out of that flavor. I'm totally ok with it being in the flavor in the next hotfix.

2017-11-27 23:18 UTC, spkellydev commented
I don't mind doing that at all. I'll try and get the changes up to you tomorrow

2017-11-29 01:58 UTC, spkellydev commented
I've made the changes to the scss for the pwa. I'm not super strong with git yet, but I can make a new pull request for just the scss if that makes things easier for you

2017-11-30 11:05 UTC, Chalarangelo requested changes
A few things need to be changed before the flavor file is ready:
1. Certain things don't make too much sense to me, could you explain the reasoning behind them?
2. You should absolutely use the module's variables and the provided code to make sure everything is compatible in future releases.
3. I am very much against breaking the `.close` element with text, I would suggest you create an extra class for that (such as `.dismiss`).

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +.modal {
These fixes are unnecessary, as they are going to be included from the `contextual` module's `.modal` class.

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +  background: rgba(0, 0, 0, 0.45);
You should be using variables, instead of hardcoding, so that future changes to the SCSS files will be applied without having to tweak the flavor again. I think these are the values you wanted to have for the modal:
```scss
$modal-name:               'modal';             // Class name for the modals
$modal-back-color:          #000;               // Background color of the modal overlay
$modal-back-opacity:        0.45;               // Background opacity of the modal overlay
$modal-close-name:         'close';             // Class name of the close element od the modal component.
$modal-close-top:           0.85rem;            // Top position of the modal component's close icon
$modal-close-right:         4.5rem;             // Right position of the modal component's close icon
```

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +    width: 100vw;
Why `width: 100vw;`? That would stretch the card to full size of the screen. Usually modals fill part of the screen. Could you elaborate as to why you made this decision? If there's something in the material guidelines I'm missing, let me know.

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +      padding: 10px;
This must be converted into `rem` units if this makes it into the flavor. **This specific fix**, if needed, is something you should keep as-is, the module file will always set this to `0`.

`10px = 0.625rem`.

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +      position: relative;
I suppose the change from `absolute` to `relative` is justified if the `.card` stays as-is (at `100vw`).

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +    overflow-y: scroll;
Could you kindly explain why this is here? I am probably missing a use-case.

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +    .section:last-child {
I am also pretty uncertain why this is here. Kindly explain, if you can.

2017-11-30 11:05 UTC, Chalarangelo commented on src/flavors/mini-pwa.scss
> +.close {
You shouldn't alter the close icon, by any means. This definitely breaks a few things. Maybe add an extra class `.dismiss` to do what you want? Make sure it's properly stylized.

2018-01-22 11:16 UTC, Chalarangelo commented
Closing as the PR is dead for about 2 months now. Feel free to reopen!

2018-01-22 11:16 UTC, closed without merging